"""Nuevo campo de la tabla user

Revision ID: 207db32107cb
Revises: 3829e69d7de5
Create Date: 2024-01-02 22:22:00.709446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207db32107cb'
down_revision = '3829e69d7de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###
