"""Nuevo campo de la tabla user

Revision ID: 634d93d73647
Revises: 207db32107cb
Create Date: 2024-01-02 22:24:36.253327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634d93d73647'
down_revision = '207db32107cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
